apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  aws_access_key_id: QUtJQTRLTEFaNjZJNlFCU01aTVQ=
  aws_secret_access_key: YldnMFptRzZMWkZzb0xhdy9MTENibU5Rc3k5WU4vWER1Y3RaZXpXTg==
